### ISSUE TITLE
生成exe失败，叫检查go'环境

### ISSUE THREAD

**Issue by lianggutian** [di0xide-U/LoaderGo#1]
生成exe失败，叫检查go'环境

**Comment by di0xide-U** [comment]
电脑里有没有go环境？ 有没有按照提示安装依赖哦？截个图看看

**Comment by Hackerb1** [comment]
我也是报这个错，vps收不到请求

**Comment by ruisika** [comment]
我也是报这个错 go也是从新装的
![image](https://github.com/di0xide-U/LoaderGo/assets/87137234/92e31645-24c2-4c39-bc6b-1ba79b62c22d)

**Comment by di0xide-U** [comment]
git 也安装了吧，记得吧git命令添加到环境变量里，因为默认安装情况下git不会添加到环境变量里

**Comment by ruisika** [comment]
十分感谢，是这个原因导致的

**Comment by Dragon-Tab** [comment]
![image](https://github.com/di0xide-U/LoaderGo/assets/53103912/5c4a11f9-a7d4-46a8-9b36-49ca49615fc9)
我也报这个错误

**Comment by di0xide-U** [comment]
依赖安装了没

**Comment by Dragon-Tab** [comment]
安装了的 重新安装依赖 重新运行 没有得到解决
