### ISSUE TITLE
程序自身报毒严重啊，自己都不免杀

### ISSUE THREAD

**Issue by ep113** [di0xide-U/LoaderGo#2]

**Comment by di0xide-U** [comment]
公开出来很快就会被杀的，包括工具本身，已经被传到微步了：https://s.threatbook.com/report/file/6b7437962d6e0b02ffb4380014dec4cff52c672ca789781e42cf52d131324fc7
不放心的话，断网虚拟机使用，工具不用联网也能用。。。。。

**Comment by ep113** [comment]
果然啊，公开等于不免杀，真难
