### ISSUE TITLE
go1.20.12生成失败，报环境问题

### ISSUE THREAD

**Issue by mybigword** [di0xide-U/LoaderGo#3]

**Comment by di0xide-U** [comment]
有图吗

**Comment by R1occccccccc** [comment]
<img width="321" alt="613ac122ae56a60c3600623fbdc30a0" src="https://github.com/di0xide-U/LoaderGo/assets/93126132/ad4015c0-78f7-4f77-adbe-e01b110b2e87">

**Comment by di0xide-U** [comment]
go环境、git环境、安装依赖，这三个都搞定了吗？

**Comment by R1occccccccc** [comment]
<img width="311" alt="791f36f6c646d308c31a588977e9459" src="https://github.com/di0xide-U/LoaderGo/assets/93126132/251dc3a9-ebbb-4950-afcb-bea93558f393">
<img width="158" alt="b6f339d8d899db0158934c7fc72a8d8" src="https://github.com/di0xide-U/LoaderGo/assets/93126132/2fa6b4a6-bc13-4bd4-acb1-95b391b19a00">
<img width="314" alt="bd11b295a665c8bd5c07b3da3ff0bb6" src="https://github.com/di0xide-U/LoaderGo/assets/93126132/75b6ba83-fe05-41f8-9671-7509069bf525">
<img width="302" alt="e964023c82fd2deee1b9f268ab6a72d" src="https://github.com/di0xide-U/LoaderGo/assets/93126132/e5306ab1-3cbc-4da2-8b3f-7e4f1e9cdbe2">
感觉依赖没问题啊师傅

**Comment by di0xide-U** [comment]
是的呢，这看起来环境都好着，奇怪，这咋生成失败了

**Comment by di0xide-U** [comment]
生成的时候是调用系统cmd，会不会是被拦截了

**Comment by R1occccccccc** [comment]
可以了师傅，感谢。我换个机器就行了，可能是哪点没配好。感谢！
